"""
Tests for AI Maintenance Features:
- Feature 1: Génération IA de checklists depuis documentation technique
- Feature 2: Génération IA de programme de maintenance préventive
- Feature 3: Analyse IA des non-conformités récurrentes
"""
import pytest
import requests
import os
import json

BASE_URL = os.environ.get('REACT_APP_BACKEND_URL', '').rstrip('/')

# Test credentials
ADMIN_EMAIL = "admin@test.com"
ADMIN_PASSWORD = "Admin123!"


class TestAIMaintenanceAPIs:
    """Test all 5 AI maintenance endpoints"""

    @pytest.fixture(autouse=True)
    def setup(self):
        """Get authentication token before tests"""
        response = requests.post(f"{BASE_URL}/api/auth/login", json={
            "email": ADMIN_EMAIL,
            "password": ADMIN_PASSWORD
        })
        assert response.status_code == 200, f"Login failed: {response.text}"
        self.token = response.json().get("access_token")
        self.headers = {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json"
        }
        self.headers_multipart = {
            "Authorization": f"Bearer {self.token}"
        }

    # ==============================================
    # Feature 1: Generate Checklist from Document
    # ==============================================
    def test_generate_checklist_endpoint_exists(self):
        """POST /api/ai-maintenance/generate-checklist should not return 404"""
        # Call without file to check endpoint exists (should return 422 not 404)
        response = requests.post(
            f"{BASE_URL}/api/ai-maintenance/generate-checklist",
            headers=self.headers_multipart
        )
        # 422 = validation error (no file), not 404 (route not found)
        assert response.status_code != 404, f"Endpoint not found! Got: {response.status_code}"
        print(f"✓ Endpoint exists, returned status {response.status_code} (expected 422 without file)")
        
    def test_generate_checklist_requires_file(self):
        """Generate checklist should require a file upload"""
        response = requests.post(
            f"{BASE_URL}/api/ai-maintenance/generate-checklist",
            headers=self.headers_multipart
        )
        # Should return 422 (Unprocessable Entity) because file is required
        assert response.status_code == 422, f"Expected 422, got {response.status_code}"
        print(f"✓ Correctly returns 422 when no file provided")

    # ==============================================
    # Feature 1: Create Checklists Batch
    # ==============================================
    def test_create_checklists_batch_endpoint_exists(self):
        """POST /api/ai-maintenance/create-checklists-batch should not return 404"""
        response = requests.post(
            f"{BASE_URL}/api/ai-maintenance/create-checklists-batch",
            headers=self.headers,
            json={"checklists": []}
        )
        assert response.status_code != 404, f"Endpoint not found! Got: {response.status_code}"
        print(f"✓ Endpoint exists, returned status {response.status_code}")

    def test_create_checklists_batch_creates_templates(self):
        """Create checklists batch should accept JSON and create templates"""
        test_data = {
            "checklists": [
                {
                    "name": "TEST_AI_Checklist_1",
                    "description": "Test checklist generated by AI test",
                    "frequence_recommandee": "MENSUEL",
                    "items": [
                        {
                            "label": "Vérifier le niveau d'huile",
                            "type": "YES_NO",
                            "required": True
                        },
                        {
                            "label": "Mesurer la température",
                            "type": "NUMERIC",
                            "unit": "°C",
                            "min_value": 20,
                            "max_value": 80,
                            "required": True
                        }
                    ]
                }
            ],
            "source_filename": "test_document.pdf"
        }
        
        response = requests.post(
            f"{BASE_URL}/api/ai-maintenance/create-checklists-batch",
            headers=self.headers,
            json=test_data
        )
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        data = response.json()
        assert data.get("success") == True, f"Expected success=True, got {data}"
        assert data.get("created_count") == 1, f"Expected 1 checklist created"
        assert len(data.get("checklists", [])) == 1
        
        # Verify created checklist data
        created = data["checklists"][0]
        assert created["name"] == "TEST_AI_Checklist_1"
        assert created["source"] == "ai_generated"
        assert len(created["items"]) == 2
        
        print(f"✓ Created {data['created_count']} checklist(s) successfully")

    # ==============================================
    # Feature 2: Generate Maintenance Program from Document
    # ==============================================
    def test_generate_maintenance_program_endpoint_exists(self):
        """POST /api/ai-maintenance/generate-maintenance-program should not return 404"""
        response = requests.post(
            f"{BASE_URL}/api/ai-maintenance/generate-maintenance-program",
            headers=self.headers_multipart
        )
        assert response.status_code != 404, f"Endpoint not found! Got: {response.status_code}"
        print(f"✓ Endpoint exists, returned status {response.status_code} (expected 422 without file)")

    def test_generate_maintenance_program_requires_file(self):
        """Generate maintenance program should require a file upload"""
        response = requests.post(
            f"{BASE_URL}/api/ai-maintenance/generate-maintenance-program",
            headers=self.headers_multipart
        )
        assert response.status_code == 422, f"Expected 422, got {response.status_code}"
        print(f"✓ Correctly returns 422 when no file provided")

    # ==============================================
    # Feature 2: Create Maintenance Batch
    # ==============================================
    def test_create_maintenance_batch_endpoint_exists(self):
        """POST /api/ai-maintenance/create-maintenance-batch should not return 404"""
        response = requests.post(
            f"{BASE_URL}/api/ai-maintenance/create-maintenance-batch",
            headers=self.headers,
            json={"programme_maintenance": []}
        )
        assert response.status_code != 404, f"Endpoint not found! Got: {response.status_code}"
        print(f"✓ Endpoint exists, returned status {response.status_code}")

    def test_create_maintenance_batch_creates_plans(self):
        """Create maintenance batch should accept JSON and create maintenance plans + checklists"""
        test_data = {
            "programme_maintenance": [
                {
                    "titre": "TEST_AI_Maintenance_Mensuelle",
                    "description": "Maintenance mensuelle générée par test IA",
                    "frequence": "MENSUEL",
                    "duree_estimee_heures": 2.0,
                    "competences_requises": "Technicien niveau 2",
                    "pieces_rechange": "Filtre huile, joint",
                    "checklist_items": [
                        {
                            "label": "Vérifier niveau huile",
                            "type": "YES_NO"
                        },
                        {
                            "label": "Mesurer pression",
                            "type": "NUMERIC",
                            "unit": "bar",
                            "min_value": 1,
                            "max_value": 10
                        }
                    ]
                }
            ],
            "equipment_id": "",
            "source_filename": "test_constructeur.pdf"
        }
        
        response = requests.post(
            f"{BASE_URL}/api/ai-maintenance/create-maintenance-batch",
            headers=self.headers,
            json=test_data
        )
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        data = response.json()
        assert data.get("success") == True, f"Expected success=True, got {data}"
        assert data.get("created_maintenance") == 1
        assert data.get("created_checklists") == 1
        assert len(data.get("maintenance", [])) == 1
        assert len(data.get("checklists", [])) == 1
        
        # Verify created maintenance plan
        pm = data["maintenance"][0]
        assert pm["titre"] == "TEST_AI_Maintenance_Mensuelle"
        assert pm["frequence"] == "MENSUEL"
        assert pm["source"] == "ai_generated"
        
        print(f"✓ Created {data['created_maintenance']} maintenance plan(s) and {data['created_checklists']} checklist(s)")

    # ==============================================
    # Feature 3: Analyze Non-conformities
    # ==============================================
    def test_analyze_nonconformities_endpoint_exists(self):
        """POST /api/ai-maintenance/analyze-nonconformities should not return 404"""
        response = requests.post(
            f"{BASE_URL}/api/ai-maintenance/analyze-nonconformities",
            headers=self.headers,
            json={"days": 90}
        )
        assert response.status_code != 404, f"Endpoint not found! Got: {response.status_code}"
        print(f"✓ Endpoint exists, returned status {response.status_code}")

    def test_analyze_nonconformities_returns_result(self):
        """Analyze non-conformities should return a result (even without historical data)"""
        response = requests.post(
            f"{BASE_URL}/api/ai-maintenance/analyze-nonconformities",
            headers=self.headers,
            json={"days": 90}
        )
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        data = response.json()
        assert data.get("success") == True, f"Expected success=True, got {data}"
        assert "data" in data, "Response should contain 'data' field"
        
        # Even without data, it should return a valid structure
        analysis = data.get("data", {})
        assert "summary" in analysis, "Analysis should contain 'summary'"
        
        print(f"✓ Analysis returned successfully: {analysis.get('summary', 'No summary')[:100]}...")

    def test_analyze_nonconformities_with_different_periods(self):
        """Analyze non-conformities with different period parameters"""
        for days in [30, 90, 180]:
            response = requests.post(
                f"{BASE_URL}/api/ai-maintenance/analyze-nonconformities",
                headers=self.headers,
                json={"days": days}
            )
            
            assert response.status_code == 200, f"Failed for {days} days: {response.status_code}"
            data = response.json()
            assert data.get("success") == True
            
            print(f"✓ Analysis with {days} days period: OK")

    # ==============================================
    # Authentication Tests
    # ==============================================
    def test_endpoints_require_authentication(self):
        """All AI maintenance endpoints should require authentication"""
        endpoints = [
            ("POST", "/api/ai-maintenance/generate-checklist"),
            ("POST", "/api/ai-maintenance/create-checklists-batch"),
            ("POST", "/api/ai-maintenance/generate-maintenance-program"),
            ("POST", "/api/ai-maintenance/create-maintenance-batch"),
            ("POST", "/api/ai-maintenance/analyze-nonconformities")
        ]
        
        for method, endpoint in endpoints:
            if method == "POST":
                response = requests.post(f"{BASE_URL}{endpoint}")
            
            # Should return 401 or 403 without token
            assert response.status_code in [401, 403], \
                f"{endpoint} should require auth, got {response.status_code}"
            print(f"✓ {endpoint} requires authentication")


# Cleanup function to remove test data
@pytest.fixture(scope="session", autouse=True)
def cleanup(request):
    """Cleanup test data after all tests"""
    def cleanup_test_data():
        try:
            # Login
            response = requests.post(f"{BASE_URL}/api/auth/login", json={
                "email": ADMIN_EMAIL,
                "password": ADMIN_PASSWORD
            })
            if response.status_code == 200:
                token = response.json().get("access_token")
                headers = {"Authorization": f"Bearer {token}"}
                
                # Get and delete TEST_ prefixed checklists
                checklists_resp = requests.get(f"{BASE_URL}/api/checklists/templates", headers=headers)
                if checklists_resp.status_code == 200:
                    for cl in checklists_resp.json().get("data", []):
                        if cl.get("name", "").startswith("TEST_"):
                            requests.delete(f"{BASE_URL}/api/checklists/templates/{cl['id']}", headers=headers)
                            print(f"Cleaned up test checklist: {cl['name']}")
                
                # Get and delete TEST_ prefixed preventive maintenance
                pm_resp = requests.get(f"{BASE_URL}/api/preventive-maintenance", headers=headers)
                if pm_resp.status_code == 200:
                    for pm in pm_resp.json().get("data", []):
                        if pm.get("titre", "").startswith("TEST_"):
                            requests.delete(f"{BASE_URL}/api/preventive-maintenance/{pm['id']}", headers=headers)
                            print(f"Cleaned up test maintenance: {pm['titre']}")
        except Exception as e:
            print(f"Cleanup warning: {e}")
    
    request.addfinalizer(cleanup_test_data)
